name: riverpod_base
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.krazighost.riverpod_base
    iosBundleIdentifier: com.krazighost.riverpodBase
